### ISSUE TITLE
Configuration file (.luacheckrc)

### ISSUE THREAD

**Issue by kankaristo** [xpol/linter-luacheck#3]
Most linters allow a project specific configuration file. Could `linter-luacheck` use `.luacheckrc` from the project's root directory? If that file isn't found, it could use `~/.atom/.luacheckrc` as a fallback.

I noticed that there are config options for global variables and warnings to ignore, but I think that it's very important that these are project-specific, not user-specific. Looking for a config file in the project directory would allow this.

The config file would also allow for more detailed configuration, like ignoring a warning only for a specific file or path, etc.

`luacheck` is very noisy by default, and it's not very useful without a configuration file...

**Comment by xpol** [comment]
@kankaristo Thanks you for your advice. I'll add this when i have time.

And any pull requests are warmly welcomed. :smile:

**Comment by mpeterv** [comment]
Next version of luacheck will look for `.luacheckrc` starting from current directory and going up to root (it's already implemented [on master branch](https://github.com/mpeterv/luacheck)). So it's able to find the config as long as it's launched from the directory containing checked file or from project's root. Also there is a way to correctly handle per-path configuration. So as long as you don't mind this not working in older luacheck versions, you won't have to change the plugin a lot, just wait a bit for the luacheck release :)

**Comment by kankaristo** [comment]
Okay, cool. I was planning on making a pull request, but you beat me to it. ;)

Thanks for implementing this, much appreciated!

**Comment by xpol** [comment]
@mpeterv You are definitely awesome!

**Comment by kankaristo** [comment]
This is working well if I run `luacheck` from the command line, but `linter-luacheck` can't find the config file.

I tried setting the working directory like this:
```coffee
         return helpers.exec(@executable, parameters,
           {
+            cwd: path.dirname file,
             stdin: editor.getText()
           }
         ).then (output) ->
```

But that doesn't work, because `linter-luacheck` is feeding `luacheck` through `stdin`. Running this also fails to find the config file:
```bash
cat file.lua | /path/to/luacheck-master/bin/luacheck -
```

@mpeterv, could `luacheck` still look for the config file even when using `stdin`? I assume you could still disable this with `--no-config`?

And by the way, how does it handle `--config`? Does it use/run both config files, or does `--config` override the one found by recursing through parent directories?

Does the recursing stop at the first config file it finds or does it combine multiple ones? Combining them could be useful so that you could have a project-wide config file and override/add some settings in a subdirectory. But you would have to run the config files in "reverse" order (closest to root first, closest to file last), and it could turn into a configuration nightmare. :P

**Comment by mpeterv** [comment]
@kankaristo indeed, it doesn't find the config when checking stdin for some reason, I'll fix that.

Currently it uses --config or default path (.luacheckrc) when searching up. So it recurses either way, and there is only one config.

I don't think there is a point in combining several configs because per-path configuration can be used within one config instead. Per-path configuration are applied in the same nightmarish order :)

**Comment by kankaristo** [comment]
> I don't think there is a point in combining several configs because per-path configuration can be used within one config instead.

That's true, and it's much easier to manage changes to the config.

Once the config file is found when using `stdin`, this should work well in `linter-luacheck`. @xpol, would you like a pull request for this (it's a really small change)?

**Comment by mpeterv** [comment]
@kankaristo should be fixed now. @xpol sorry to hijacking your issue tracker :)

**Comment by kankaristo** [comment]
Now it's working with `linter-luacheck` if I give it the `cwd` option. :)

**Comment by xpol** [comment]
@kankaristo Thank you!
@mpeterv be my guest.

**Comment by xpol** [comment]
@kankaristo 1.0.3 now set the `cwd` options.

**Comment by kankaristo** [comment]
I'll close the issue and wait for the new version of `luacheck` to hit the shelves. :+1:
