### ISSUE TITLE
Disabled linter-luacheck is throwing error after update

### ISSUE THREAD

**Issue by polarathene** [xpol/linter-luacheck#6]
I've got a separate error related to linter-eslint already reported. Just updated my linter packages and for some reason my disabled linter-luacheck is throwing an error while working on a js file? Was slightly confused why I couldn't submit an issue until I realized the repo linked from the package url is a fork of this one, might help to point that out in the readme for error reports?

![atom linter-luacheck error](http://i.imgur.com/zVXTO2j.png)

**Comment by polarathene** [comment]
I've disabled linter-eslint, linter-luacheck is no longer throwing the error, at least there is no visual popup. If I enable linter-eslint again and try to work on the js file I'll get the same errors as the screenshot shows. So perhaps linter-eslint is somehow at fault here, or linter-luacheck is throwing the error but it doesn't display til another error is thrown?

**Comment by xpol** [comment]
Close because the log show error about ESlint.
